%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% CST SRR 自动化仿真脚本 - MATLAB 主控程序
% 功能: 调用 CST Microwave Studio 创建 SRR-loaded WR-28 波导模型
%       运行仿真并提取 S 参数, 拟合 Lorentz 模型参数
% 作者: Auto-generated for thesis project
% 日期: 2026-01-18
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% 1. 配置参数
clc; clear; close all;

% 添加当前目录到 MATLAB 路径 (确保函数可被调用)
script_dir = fileparts(mfilename('fullpath'));
if isempty(script_dir)
    script_dir = pwd;
end
addpath(script_dir);
fprintf('工作目录: %s\n', script_dir);


% ---------------------------
% 1.1 CST 环境配置
% ---------------------------
CST_VERSION = '2023';  % 修改为你的 CST 版本
PROJECT_NAME = 'SRR_WR28_Lorentz';
PROJECT_PATH = pwd;    % 当前目录, 可修改

% ---------------------------
% 1.2 物理结构参数 (WR-28 + SRR)
% ---------------------------
params = struct();

% WR-28 波导尺寸 (Ka 波段: 26.5-40 GHz)
params.waveguide.a = 7.112;        % 波导宽度 (mm)
params.waveguide.b = 3.556;        % 波导高度 (mm)
params.waveguide.length = 20;      % 波导总长度 (mm)

% SRR 几何参数 (谐振 ~33 GHz, 带宽 ~500 MHz)
params.srr.L_out = 2.12;           % 外环边长 (mm)
params.srr.L_in = 1.48;            % 内环边长 (mm)
params.srr.w = 0.2;                % 环宽 (mm)
params.srr.g = 0.6;                % 开口宽度 (mm), 增大以加宽谐振带宽
params.srr.position_z = 10;        % SRR 在波导中的位置 (mm)

% 基板参数 (Rogers 5880, 略增 tan_d 以加宽谐振带宽)
params.substrate.h = 0.254;        % 基板厚度 (mm)
params.substrate.eps_r = 2.2;      % 相对介电常数
params.substrate.tan_d = 0.02;     % 损耗角正切 (增大以加宽谐振带宽)

% 金属参数 (降低 sigma 增加导体损耗以加宽带宽)
params.metal.t = 0.035;            % 铜箔厚度 (mm)
params.metal.sigma = 1e7;          % 电导率 (S/m)

% ---------------------------
% 1.3 仿真参数
% ---------------------------
params.sim.f_min = 30e9;           % 起始频率 (Hz)
params.sim.f_max = 40e9;           % 终止频率 (Hz)
params.sim.n_points = 1000;        % 频率采样点数 (减少以缩短仿真时间)

% ---------------------------
% 1.4 有效厚度 (用于 Lorentz 拟合)
% ---------------------------
params.d_eff = 3e-3;               % 有效厚度 (m) - 可调整

fprintf('========================================\n');
fprintf('CST SRR 自动化仿真脚本\n');
fprintf('========================================\n');
fprintf('波导: WR-28 (%.3f x %.3f mm)\n', params.waveguide.a, params.waveguide.b);
fprintf('SRR 外环: %.2f mm, 预期谐振: ~33 GHz\n', params.srr.L_out);
fprintf('频率范围: %.1f - %.1f GHz\n', params.sim.f_min/1e9, params.sim.f_max/1e9);
fprintf('========================================\n\n');

%% 2. 尝试连接 CST (COM 接口)
fprintf('正在尝试连接 CST Microwave Studio...\n');

try
    % 创建 CST 应用程序对象
    cst = actxserver('CSTStudio.Application');
    fprintf('✓ CST 连接成功!\n');
    
    % 创建新项目
    mws = cst.invoke('NewMWS');
    fprintf('✓ 新项目创建成功!\n');
    
    CST_CONNECTED = true;
    
catch ME
    fprintf('✗ CST 连接失败: %s\n', ME.message);
    fprintf('\n--- 备选方案 ---\n');
    fprintf('请使用以下方式手动创建模型:\n');
    fprintf('1. 打开 CST Microwave Studio\n');
    fprintf('2. 运行 VBA 宏: CST_SRR_Template.bas\n');
    fprintf('3. 导出 S 参数为 .csv 或 .s2p 格式\n');
    fprintf('4. 使用本脚本的 "离线模式" 加载数据\n');
    fprintf('-----------------------------------\n\n');
    
    CST_CONNECTED = false;
end

%% 3. 如果连接成功, 创建模型
if CST_CONNECTED
    fprintf('\n正在创建 SRR-loaded WR-28 模型...\n');
    
    try
        % CST COM 接口需要通过 VBA 命令字符串执行
        % 使用 AddToHistory 方法发送 VBA 命令
        
        % 3.1 设置单位 - 通过 VBA 命令字符串
        vba_units = [...
            'With Units' newline ...
            '  .Geometry "mm"' newline ...
            '  .Frequency "GHz"' newline ...
            '  .Time "ns"' newline ...
            'End With'];
        invoke(mws, 'AddToHistory', 'define units', vba_units);
        fprintf('  ✓ 单位设置完成\n');
        
        % 3.2 设置频率范围
        vba_freq = sprintf('Solver.FrequencyRange "%.2f", "%.2f"', ...
            params.sim.f_min/1e9, params.sim.f_max/1e9);
        invoke(mws, 'AddToHistory', 'define frequency range', vba_freq);
        fprintf('  ✓ 频率范围设置完成\n');
        
        % 3.3 创建材料 - Rogers 5880
        vba_material = [...
            'With Material' newline ...
            '  .Reset' newline ...
            '  .Name "Rogers5880"' newline ...
            '  .Type "Normal"' newline ...
            sprintf('  .Epsilon "%.2f"', params.substrate.eps_r) newline ...
            sprintf('  .TanD "%.6f"', params.substrate.tan_d) newline ...
            '  .Colour "0.8", "0.6", "0.2"' newline ...
            '  .Create' newline ...
            'End With'];
        invoke(mws, 'AddToHistory', 'define material Rogers5880', vba_material);
        % 低电导率金属 (用于 SRR, 增加损耗以加宽带宽)
        vba_metal = [...
            'With Material' newline ...
            '  .Reset' newline ...
            '  .Name "SRR_Metal"' newline ...
            '  .Type "Normal"' newline ...
            '  .Epsilon "1"' newline ...
            '  .Mue "1"' newline ...
            sprintf('  .Sigma "%.0f"', params.metal.sigma) newline ...
            '  .Colour "0.6", "0.6", "0.6"' newline ...
            '  .Create' newline ...
            'End With'];
        invoke(mws, 'AddToHistory', 'define material SRR_Metal', vba_metal);
        fprintf('  ✓ 材料定义完成\n');
        
        % 3.4 创建波导空气腔
        vba_wg = [...
            'With Brick' newline ...
            '  .Reset' newline ...
            '  .Name "Air_Cavity"' newline ...
            '  .Component "Waveguide"' newline ...
            '  .Material "Vacuum"' newline ...
            sprintf('  .Xrange "%.4f", "%.4f"', -params.waveguide.a/2, params.waveguide.a/2) newline ...
            sprintf('  .Yrange "%.4f", "%.4f"', -params.waveguide.b/2, params.waveguide.b/2) newline ...
            sprintf('  .Zrange "0", "%.4f"', params.waveguide.length) newline ...
            '  .Create' newline ...
            'End With'];
        invoke(mws, 'AddToHistory', 'define brick: Waveguide', vba_wg);
        fprintf('  ✓ 波导腔体创建完成\n');
        
        % 3.5 创建 SRR 外环 (y 居中以增强与 TE10 场耦合, 加宽带宽)
        L_out = params.srr.L_out;
        L_in = params.srr.L_in;
        z_pos = params.srr.position_z;
        y_metal_lo = -params.metal.t/2;
        y_metal_hi = params.metal.t/2;
        y_sub_lo = y_metal_lo - params.substrate.h;
        y_sub_hi = y_metal_lo;
        
        vba_srr_outer = [...
            'With Brick' newline ...
            '  .Reset' newline ...
            '  .Name "SRR_Outer"' newline ...
            '  .Component "SRR"' newline ...
            '  .Material "SRR_Metal"' newline ...
            sprintf('  .Xrange "%.4f", "%.4f"', -L_out/2, L_out/2) newline ...
            sprintf('  .Yrange "%.4f", "%.4f"', y_metal_lo, y_metal_hi) newline ...
            sprintf('  .Zrange "%.4f", "%.4f"', z_pos - L_out/2, z_pos + L_out/2) newline ...
            '  .Create' newline ...
            'End With'];
        invoke(mws, 'AddToHistory', 'define brick: SRR_Outer', vba_srr_outer);
        
        % 3.6 创建 SRR 内部开口
        vba_srr_inner = [...
            'With Brick' newline ...
            '  .Reset' newline ...
            '  .Name "SRR_Inner"' newline ...
            '  .Component "SRR"' newline ...
            '  .Material "Vacuum"' newline ...
            sprintf('  .Xrange "%.4f", "%.4f"', -L_in/2, L_in/2) newline ...
            sprintf('  .Yrange "%.4f", "%.4f"', y_metal_lo, y_metal_hi) newline ...
            sprintf('  .Zrange "%.4f", "%.4f"', z_pos - L_in/2, z_pos + L_in/2) newline ...
            '  .Create' newline ...
            'End With'];
        invoke(mws, 'AddToHistory', 'define brick: SRR_Inner', vba_srr_inner);
        
        % 布尔减法 (外环减内环)
        vba_subtract = 'Solid.Subtract "SRR:SRR_Outer", "SRR:SRR_Inner"';
        invoke(mws, 'AddToHistory', 'boolean subtract', vba_subtract);
        % 3.6b 创建 SRR 开口缝 (环上开缝以加宽谐振带宽)
        g = params.srr.g;
        vba_srr_gap = [...
            'With Brick' newline ...
            '  .Reset' newline ...
            '  .Name "SRR_Gap"' newline ...
            '  .Component "SRR"' newline ...
            '  .Material "Vacuum"' newline ...
            sprintf('  .Xrange "%.4f", "%.4f"', -g/2, g/2) newline ...
            sprintf('  .Yrange "%.4f", "%.4f"', y_metal_lo, y_metal_hi) newline ...
            sprintf('  .Zrange "%.4f", "%.4f"', z_pos + L_in/2, z_pos + L_out/2) newline ...
            '  .Create' newline ...
            'End With'];
        invoke(mws, 'AddToHistory', 'define brick: SRR_Gap', vba_srr_gap);
        vba_subtract_gap = 'Solid.Subtract "SRR:SRR_Outer", "SRR:SRR_Gap"';
        invoke(mws, 'AddToHistory', 'boolean subtract gap', vba_subtract_gap);
        fprintf('  ✓ SRR 结构创建完成\n');
        
        % 3.7 创建基板 (金属层下方)
        vba_sub = [...
            'With Brick' newline ...
            '  .Reset' newline ...
            '  .Name "Substrate"' newline ...
            '  .Component "SRR"' newline ...
            '  .Material "Rogers5880"' newline ...
            sprintf('  .Xrange "%.4f", "%.4f"', -params.waveguide.a/2, params.waveguide.a/2) newline ...
            sprintf('  .Yrange "%.4f", "%.4f"', y_sub_lo, y_sub_hi) newline ...
            sprintf('  .Zrange "%.4f", "%.4f"', z_pos - 1.5, z_pos + 1.5) newline ...
            '  .Create' newline ...
            'End With'];
        invoke(mws, 'AddToHistory', 'define brick: Substrate', vba_sub);
        fprintf('  ✓ 基板创建完成\n');
        
        % 3.8 创建端口1
        vba_port1 = [...
            'With Port' newline ...
            '  .Reset' newline ...
            '  .PortNumber "1"' newline ...
            '  .Label "Port1"' newline ...
            '  .NumberOfModes "1"' newline ...
            '  .Orientation "zmin"' newline ...
            '  .Coordinates "Full"' newline ...
            sprintf('  .Xrange "%.4f", "%.4f"', -params.waveguide.a/2, params.waveguide.a/2) newline ...
            sprintf('  .Yrange "%.4f", "%.4f"', -params.waveguide.b/2, params.waveguide.b/2) newline ...
            '  .Zrange "0", "0"' newline ...
            '  .Create' newline ...
            'End With'];
        invoke(mws, 'AddToHistory', 'define port 1', vba_port1);
        
        % 3.9 创建端口2
        vba_port2 = [...
            'With Port' newline ...
            '  .Reset' newline ...
            '  .PortNumber "2"' newline ...
            '  .Label "Port2"' newline ...
            '  .NumberOfModes "1"' newline ...
            '  .Orientation "zmax"' newline ...
            '  .Coordinates "Full"' newline ...
            sprintf('  .Xrange "%.4f", "%.4f"', -params.waveguide.a/2, params.waveguide.a/2) newline ...
            sprintf('  .Yrange "%.4f", "%.4f"', -params.waveguide.b/2, params.waveguide.b/2) newline ...
            sprintf('  .Zrange "%.4f", "%.4f"', params.waveguide.length, params.waveguide.length) newline ...
            '  .Create' newline ...
            'End With'];
        invoke(mws, 'AddToHistory', 'define port 2', vba_port2);
        fprintf('  ✓ 端口创建完成\n');
        
        % 3.10 设置边界条件
        vba_boundary = [...
            'With Boundary' newline ...
            '  .Xmin "electric"' newline ...
            '  .Xmax "electric"' newline ...
            '  .Ymin "electric"' newline ...
            '  .Ymax "electric"' newline ...
            '  .Zmin "open"' newline ...
            '  .Zmax "open"' newline ...
            'End With'];
        invoke(mws, 'AddToHistory', 'define boundary', vba_boundary);
        fprintf('  ✓ 边界条件设置完成\n');
        
        fprintf('\n✓ 模型创建完成!\n');
        
        % 3.11 保存项目
        project_file = fullfile(PROJECT_PATH, [PROJECT_NAME '.cst']);
        invoke(mws, 'SaveAs', project_file, 'false');
        fprintf('✓ 项目已保存: %s\n', project_file);
        
        
        
        SIM_COMPLETED = false;  % 需要手动运行
        DATA_READY = false;
        
    catch ME
        fprintf('\n✗ CST 模型创建失败: %s\n', ME.message);
        fprintf('错误位置: %s (行 %d)\n', ME.stack(1).name, ME.stack(1).line);
        fprintf('\n将切换到离线演示模式...\n\n');
        CST_CONNECTED = false;
        SIM_COMPLETED = false;
        DATA_READY = false;
    end
end